site_name: Ian Barnes
site_description: Random thoughts
site_url: https://www.ianbarnes.me.uk
theme:
  name: material
  custom_dir: overrides
  palette:
      scheme: default
      primary: white
      accent: blue
  logo: assets/beanie.jpg
  favicon: assets/favicon.ico
  font:
    text: "IM Fell English"
  features:
    - navigation.indexes
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: material/email
      link: mailto:ianbarnes1963@gmail.com
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/barnes1463
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/ianbarnes1963
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/barnes1463
    - icon: simple/github
      link: https://github.com/ian-barnes
copyright: Copyright &copy; 2020–2025 Ian Barnes
plugins:
  - blog:
      enabled: true
      # blog_dir: blog
      blog_dir: .
      blog_toc: false
      post_dir: "{blog}/posts"
      post_url_max_categories: 1
      post_slugify_separator: "-"
      post_excerpt_max_authors: 1
      post_excerpt_max_categories: 5
      post_excerpt_separator: <!-- more -->
      post_readtime: false
      post_date_format: "EEEE d MMMM yyyy"
      # post_readtime_words_per_minute: 265
      # archive: true
      archive: false
      # archive_name: Archive
      # archive_pagination: true
      # archive_pagination_per_page: 10
      # archive_toc: false
      # categories: false
      # categories_name: Categories
      # categories_slugify_separator: "-"
      # categories_pagination: true
      # categories_pagination_per_page: 10
      # categories_toc: false
      # authors: false
      # authors_file: "{blog}/.authors.yml"
      # authors_profiles: false
      # authors_profiles_name: Authors
      # authors_profiles_pagination: true
      # authors_profiles_pagination_per_page: 10
      # authors_profiles_toc: false
      pagination: false
      # pagination_per_page: 10
      # pagination_keep_content: false
      draft: false
      # draft_on_serve: true
      # draft_if_future_date: false
  - rss:
      enabled: true
      date_from_meta:
        as_creation: date
      abstract_chars_count: 160
      abstract_delimiter: <!-- more -->
      comments_path: "null"
      feed_ttl: 1440
      image: "null"
      json_feed_enabled: false
      length: 20
      match_path: .*
      pretty_print: false
      rss_feed_enabled: true
      use_git: true
      use_material_social_cards: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: auto
      height: auto
      zoomable: true
      draggable: true
      auto_caption: true
      caption_position: bottom
      background: white
      shadow: true
      manual: false
nav:
  - Home: index.md
  - About: about.md
